# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170805_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleonmoderation',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ArticleOnModeration',
        ),
    ]
