# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170814_1928'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
    ]
